options:
  prometheus_server_host:
    type: string
    default: ""
  prometheus_server_port:
    type: int
    default:
  multitenant_label:
    type: string
    description: |
      Prometheus Configurer has been designed to support multiple tenants. This label can be used
      to restrict the alerting rules in Prometheus, so that each rule can only be triggered by 
      metrics with matching label.
    default: networkID
